import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/lib/auth/options';
import { createEventViaWebhook } from '@/app/lib/n8n-webhook';
import { eventSchema, validateAndSanitize } from '@/app/lib/validation';

// POST - Create new event (WEBHOOK ONLY - NO DATABASE WRITE)
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session || !['SUPER_ADMIN', 'ADMIN', 'ORGANIZATOR'].includes(session.user.role)) {
      return NextResponse.json({ error: 'Yetkisiz erişim' }, { status: 403 });
    }

    const body = await request.json();
    const {
      baslik,
      slug,
      tip,
      kapsam,
      aciklama,
      baslangic_tarihi,
      bitis_tarihi,
      son_basvuru_tarihi,
      erken_kayit_tarihi,
      yer,
      adres,
      online,
      ucret,
      erken_kayit_ucret,
      ogrenci_ucret,
      max_katilimci,
      durum,
      logo_url,
      gorsel_url,
      ucretsiz,
    } = body;

    // Validate input using Zod schema
    const validation = validateAndSanitize({
      baslik,
      slug,
      tip,
      kapsam,
      baslangic_tarihi,
      bitis_tarihi,
      son_basvuru_tarihi,
      erken_kayit_tarihi,
      yer,
      ucret: ucret !== undefined ? parseFloat(ucret) : undefined,
      erken_kayit_ucret: erken_kayit_ucret ? parseFloat(erken_kayit_ucret) : undefined,
      ogrenci_ucret: ogrenci_ucret ? parseFloat(ogrenci_ucret) : undefined,
      ucretsiz: ucretsiz !== undefined ? ucretsiz : false,
    }, eventSchema);

    if (!validation.success) {
      return NextResponse.json({
        error: 'Validasyon hatası',
        details: validation.errors
      }, { status: 400 });
    }

    const validatedData = validation.data;

    // WEBHOOK-ONLY: Send to n8n webhook - webhook will handle database write
    const webhookResponse = await createEventViaWebhook({
      metadata: {
        requestId: `event-create-${Date.now()}`,
        timestamp: new Date().toISOString(),
        source: 'web-app',
        version: '1.0',
      },
      requestedBy: {
        userId: session.user.id || '',
        userEmail: session.user.email || '',
        userName: `${session.user.ad || ''} ${session.user.soyad || ''}`.trim() || session.user.name || '',
        userRole: session.user.role || 'ADMIN',
      },
      event: {
        eventId: '', // Will be generated by webhook
        baslik: validatedData.baslik,
        slug: validatedData.slug,
        tip: validatedData.tip,
        kapsam: validatedData.kapsam,
        aciklama: aciklama || null,
        baslangic_tarihi: validatedData.baslangic_tarihi,
        bitis_tarihi: validatedData.bitis_tarihi,
        son_basvuru_tarihi: validatedData.son_basvuru_tarihi,
        erken_kayit_tarihi: validatedData.erken_kayit_tarihi || null,
        yer: validatedData.yer,
        adres: adres || null,
        online: online || false,
        ucret: validatedData.ucret,
        erken_kayit_ucret: validatedData.erken_kayit_ucret || null,
        ogrenci_ucret: validatedData.ogrenci_ucret || null,
        max_katilimci: max_katilimci ? parseInt(max_katilimci) : null,
        durum: durum || 'TASLAK',
        logo_url: logo_url || null,
        gorsel_url: gorsel_url || null,
      },
    });

    // If webhook fails, return error
    if (!webhookResponse.success) {
      return NextResponse.json(
        {
          error: 'Etkinlik webhook sistemi yanıt vermedi. Lütfen tekrar deneyin.',
          details: webhookResponse.error
        },
        { status: 500 }
      );
    }

    // Return webhook response (contains eventId generated by webhook)
    return NextResponse.json({
      event: webhookResponse.data,
      message: 'Etkinlik başarıyla oluşturuldu (webhook üzerinden)'
    }, { status: 201 });
  } catch (error: any) {
    console.error('Event creation error:', error);
    return NextResponse.json(
      { error: 'Etkinlik oluşturulurken bir hata oluştu', details: error.message },
      { status: 500 }
    );
  }
}
