import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/lib/auth/options';
import prisma from '@/app/lib/prisma';
import { createEventViaWebhook } from '@/app/lib/n8n-webhook';

// POST - Create new event
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session || !['SUPER_ADMIN', 'ADMIN', 'ORGANIZATOR'].includes(session.user.role)) {
      return NextResponse.json({ error: 'Yetkisiz erişim' }, { status: 403 });
    }

    const body = await request.json();
    const {
      baslik,
      slug,
      tip,
      aciklama,
      baslangic_tarihi,
      bitis_tarihi,
      son_basvuru_tarihi,
      yer,
      adres,
      online,
      ucret,
      erken_kayit_ucret,
      ogrenci_ucret,
      erken_kayit_tarihi,
      max_katilimci,
      durum,
    } = body;

    // Validate required fields
    if (!baslik || !slug || !baslangic_tarihi || !bitis_tarihi || !son_basvuru_tarihi || !yer) {
      return NextResponse.json(
        { error: 'Eksik zorunlu alanlar' },
        { status: 400 }
      );
    }

    // Check if slug already exists
    const existingEvent = await prisma.event.findUnique({
      where: { slug },
    });

    if (existingEvent) {
      return NextResponse.json(
        { error: 'Bu URL slug zaten kullanımda' },
        { status: 400 }
      );
    }

    // WEBHOOK-ONLY: Send to n8n webhook first
    const webhookResponse = await createEventViaWebhook({
      metadata: {
        requestId: `event-create-${Date.now()}`,
        timestamp: new Date().toISOString(),
        source: 'web-app',
        version: '1.0',
      },
      requestedBy: {
        userId: session.user.id || '',
        userEmail: session.user.email || '',
        userName: session.user.name || '',
      },
      event: {
        eventId: '', // Will be generated by webhook
        baslik,
        slug,
        tip: tip || 'KONGRE',
        kapsam: body.kapsam || 'ULUSAL',
        aciklama,
        baslangic_tarihi: new Date(baslangic_tarihi).toISOString(),
        bitis_tarihi: new Date(bitis_tarihi).toISOString(),
        son_basvuru_tarihi: new Date(son_basvuru_tarihi).toISOString(),
        erken_kayit_tarihi: erken_kayit_tarihi ? new Date(erken_kayit_tarihi).toISOString() : null,
        yer,
        adres: adres || null,
        online: online || false,
        ucret: parseFloat(ucret) || 0,
        erken_kayit_ucret: parseFloat(erken_kayit_ucret) || null,
        ogrenci_ucret: parseFloat(ogrenci_ucret) || null,
        max_katilimci: parseInt(max_katilimci) || null,
        durum: durum || 'TASLAK',
      },
    });

    // If webhook fails, return error
    if (!webhookResponse.success) {
      return NextResponse.json(
        { error: 'Etkinlik webhook sistemi yanıt vermedi. Lütfen tekrar deneyin.' },
        { status: 500 }
      );
    }

    // Webhook succeeded - now create in database with webhook response data
    const webhookEventData = webhookResponse.data;
    const event = await prisma.event.create({
      data: {
        id: webhookEventData.eventId || undefined,
        baslik,
        slug,
        tip: tip || 'KONGRE',
        kapsam: body.kapsam || 'ULUSAL',
        aciklama,
        baslangic_tarihi: new Date(baslangic_tarihi),
        bitis_tarihi: new Date(bitis_tarihi),
        son_basvuru_tarihi: new Date(son_basvuru_tarihi),
        yer,
        adres,
        online: online || false,
        ucret: parseFloat(ucret) || 0,
        erken_kayit_ucret: parseFloat(erken_kayit_ucret) || 0,
        ogrenci_ucret: parseFloat(ogrenci_ucret) || 0,
        erken_kayit_tarihi: erken_kayit_tarihi ? new Date(erken_kayit_tarihi) : null,
        max_katilimci: parseInt(max_katilimci) || null,
        durum: durum || 'TASLAK',
      },
    });

    return NextResponse.json({ event }, { status: 201 });
  } catch (error) {
    console.error('Event creation error:', error);
    return NextResponse.json(
      { error: 'Etkinlik oluşturulurken bir hata oluştu' },
      { status: 500 }
    );
  }
}
